import { ProviderConfig } from '@/types/provider'

export const defaultProviders: ProviderConfig[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai',
    apiBaseUrl: 'https://api.openai.com/v1',
    apiKey: '',
    enabled: true,
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        maxTokens: 128000,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 2.5, outputPerMillion: 10 },
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        maxTokens: 128000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 0.15, outputPerMillion: 0.6 },
      },
      {
        id: 'o1',
        name: 'o1',
        maxTokens: 200000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 15, outputPerMillion: 60 },
      },
      {
        id: 'o3-mini',
        name: 'o3-mini',
        maxTokens: 200000,
        supportsVision: false,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 1.1, outputPerMillion: 4.4 },
      },
      {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
        maxTokens: 128000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 10, outputPerMillion: 30 },
      },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'anthropic',
    apiBaseUrl: 'https://api.anthropic.com',
    apiKey: '',
    enabled: true,
    models: [
      {
        id: 'claude-sonnet-4-20250514',
        name: 'Claude Sonnet 4',
        maxTokens: 200000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: false,
        pricing: { inputPerMillion: 3, outputPerMillion: 15 },
      },
      {
        id: 'claude-3-5-haiku-20241022',
        name: 'Claude 3.5 Haiku',
        maxTokens: 200000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: false,
        pricing: { inputPerMillion: 1, outputPerMillion: 5 },
      },
      {
        id: 'claude-opus-4-20250514',
        name: 'Claude Opus 4',
        maxTokens: 200000,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: false,
        pricing: { inputPerMillion: 15, outputPerMillion: 75 },
      },
    ],
  },
  {
    id: 'google',
    name: 'Google AI',
    type: 'google',
    apiBaseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    apiKey: '',
    enabled: true,
    models: [
      {
        id: 'gemini-2.5-pro-preview-06-05',
        name: 'Gemini 2.5 Pro',
        maxTokens: 1048576,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 1.25, outputPerMillion: 10 },
      },
      {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        maxTokens: 1048576,
        supportsVision: true,
        supportsAudio: true,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 0.1, outputPerMillion: 0.4 },
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    type: 'deepseek',
    apiBaseUrl: 'https://api.deepseek.com/v1',
    apiKey: '',
    enabled: true,
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek V3',
        maxTokens: 65536,
        supportsVision: false,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
        pricing: { inputPerMillion: 0.27, outputPerMillion: 1.1 },
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1',
        maxTokens: 65536,
        supportsVision: false,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: false,
        supportsJsonMode: false,
        pricing: { inputPerMillion: 0.55, outputPerMillion: 2.19 },
      },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    type: 'ollama',
    apiBaseUrl: 'http://192.168.31.75:8000/v1',
    apiKey: 'ollama',
    enabled: true,
    models: [
      {
        id: 'gemma4-31b-local:latest',
        name: 'Gemma 4 31B (Q4_K_M)',
        maxTokens: 131072,
        supportsVision: true,
        supportsAudio: false,
        supportsStreaming: true,
        supportsToolUse: true,
        supportsJsonMode: true,
      },
    ],
  },
]
